# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44cf6c274f0e5fcdc07825d4f3625384fc79fe666942b4b3265ee18cd6eeb62d5b5b4df8f979b22a49af9a19a0cb9cfd8f83be5bd8334aedb04628ea75d61599

test:
  secret_key_base: a38f2e8123bde1dd21db18b86559c5f496b8cb77356367b92a2b139daddc0b00794b48a81585d5370080c6f4f396fe923d2989df415bc759627dde2db71685be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
