# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e98841aeb68652766433d35d2c00752c42c6bde5028e2fb611a3bd156c668140cb9f58bc4ed55072230c697df504e544acfd2c3b000c5e765d458a3c25d0549

test:
  secret_key_base: 6616342ddb104d524d7090bc2fbadb38c170e4e2620c79381fc34c7c1dc19b6753594be8caf2b4edf877ced15e0b221f1c72d25d1b788dc567247268755b08b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
